export const products = [
  {
    id: 1,
    name: 'Skate Completo cbgang beiseball',
    price: 349.99,
    image: 'produtos/skate/cbgangbeiseball.png',
    category: 'completos',
  },
  {
    id: 2,
    name: 'Skate Completo cbgang stella',
    price: 349.99,
    image: 'produtos/skate/cbgangstella.png',
    category: 'completos',
  },
  {
    id: 3,
    name: 'Skate Completo Picolé Quebrado graffity',
    price: 549.99,
    image: 'produtos/skate/skatemontadoGraffity.png',
    category: 'completos',
  },
  {
    id: 4,
    name: 'Shape Picolé Quebrado camuflado',
    price: 219.99,
    image: 'produtos/shapes/camuflado.png',
    category: 'shapes',
  },
  {
    id: 5,
    name: 'Shape Picolé Quebrado graffity',
    price: 219.99,
    image: 'produtos/shapes/graffiti.png',
    category: 'shapes',
  },
  {
    id: 6,
    name: 'Shape Picolé Quebrado muro',
    price: 219.99,
    image: 'produtos/shapes/MUROGRAFITTI.png',
    category: 'shapes',
  },
  {
    id: 7,
    name: 'Parafuso de Base',
    price: 24.99,
    image: 'produtos/parafuso/parafuso.jpg',
    category: 'parafusos',
  },
  {
    id: 7,
    name: 'Parafuso de Base Element',
    price: 39.99,
    image: 'produtos/parafuso/parafusoelement.png',
    category: 'parafusos',
  },
  {
    id: 7,
    name: 'Parafuso de Base chocolate',
    price: 39.99,
    image: 'produtos/parafuso/parafusochocolate.png',
    category: 'parafusos',
  },
  // {
  //   id: 7,
  //   name: 'Parafuso de Base thrasher',
  //   price: 39.99,
  //   image: 'produtos/parafuso/parafusotrasher.png',
  //   category: 'parafusos',
  // },
  // {
  //   id: 8,
  //   name: 'Boné Picolé Quebrado Esgotado',
  //   price: 0,
  //   image: 'produtos/bone/BONEBLACKRED.jpg',
  //   category: 'bones',
  // },
  // {
  //   id: 9,
  //   name: 'Kit Amortecedores Black Sheep',
  //   price: 29.99,
  //   image: 'produtos/amortecedor/amortecedores.jpg',
  //   category: 'amortecedores',
  // },
  // {
  //   id: 10,
  //   name: 'Lixa Vinho',
  //   price: 59.99,
  //   image: 'produtos/lixavinho.jpg',
  //   category: 'acessorios',
  // },
  {
    id: 11,
    name: 'Lixa Nacional',
    price: 29.99,
    image: 'produtos/lixa.webp',
    category: 'acessorios',
  },
  {
    id: 12,
    name: 'Rolamento Abec9',
    price: 45.99,
    image: 'produtos/rolamento/abec9.jpg',
    category: 'rolamentos',
  },
  {
    id: 13,
    name: 'Rolamento Bones Big Balls',
    price: 144.99,
    image: 'produtos/rolamento/bonesbill.jpg',
    category: 'rolamentos',
  },
  {
    id: 14,
    name: 'Rolamento Bones Reds',
    price: 144.99,
    image: 'produtos/rolamento/bonesred.jpg',
    category: 'rolamentos',
  },
  {
    id: 15,
    name: 'Rolamento Bones Super',
    price: 144.99,
    image: 'produtos/rolamento/bonessuper.jpg',
    category: 'rolamentos',
  },
  // {
  //   id: 16,
  //   name: 'Shape Anti action',
  //   price: 99.99,
  //   image: 'produtos/shapes/anti2.jpg',
  //   category: 'shapes',
  // },
  {
    id: 17,
    name: 'Rodas Next',
    price: 94.99,
    image: 'produtos/next.webp',
    category: 'rodas',
  },
  // {
  //   id: 18,
  //   name: 'truck skate',
  //   price: 119.99,
  //   image: 'produtos/skate/truck.jpg',
  //   category: 'trucks',
  // },
  {
    id: 19,
    name: 'Parafuso colorido PIG',
    price: 39.99,
    image: 'produtos/parafuso/parafusopig.jpg',
    category: 'parafusos',
  },
  {
    id: 20,
    name: 'porca color nuts dourada',
    price: 24.99,
    image: 'produtos/parafuso/porcadourada.jpg',
    category: 'rodas',
  },
  // {
  //   id: 21,
  //   name: 'porca color nuts lilás',
  //   price: 24.99,
  //   image: 'produtos/parafuso/porcalilas.jpg',
  //   category: 'rodas',
  // },
  {
    id: 22,
    name: 'porca color nuts prata',
    price: 24.99,
    image: 'produtos/parafuso/porcaprata.jpg',
    category: 'rodas',
  },
];
