export const products = [
  {
    id: 1,
    name: 'Skate Completo cbgang beiseball',
    price: 349.99,
    image: 'produtos/skate/cbgangbeiseball.png',
    category: 'completos',
  },
  {
    id: 2,
    name: 'Kit Segurança Shock Infantil (joelheira, cotoveleira)',
    price: 75.0,
    image: 'news/kit_seguranca.jpg',
    category: 'acessorios',
  },
  {
    id: 3,
    name: 'Skate Completo Picolé Quebrado graffity',
    price: 549.99,
    image: 'produtos/skate/skatemontadoGraffity.png',
    category: 'completos',
  },
  {
    id: 4,
    name: 'Shape Picolé Quebrado camuflado',
    price: 219.99,
    image: 'produtos/shapes/camuflado.png',
    category: 'shapes',
  },
  {
    id: 5,
    name: 'Shape Picolé Quebrado graffity',
    price: 219.99,
    image: 'produtos/shapes/graffiti.png',
    category: 'shapes',
  },
  {
    id: 6,
    name: 'Shape Picolé Quebrado muro',
    price: 219.99,
    image: 'produtos/shapes/MUROGRAFITTI.png',
    category: 'shapes',
  },
  {
    id: 7,
    name: 'Parafuso de Base',
    price: 24.99,
    image: 'produtos/parafuso/parafuso.jpg',
    category: 'parafusos',
  },
  {
    id: 7,
    name: 'Parafuso de Base Element',
    price: 44.99,
    image: 'produtos/parafuso/parafusoelement.png',
    category: 'parafusos',
  },
  {
    id: 7,
    name: 'Parafuso de Base chocolate',
    price: 44.99,
    image: 'produtos/parafuso/parafusochocolate.png',
    category: 'parafusos',
  },
  {
    id: 7,
    name: 'Amortecedor Laranja',
    price: 30.0,
    image: 'news/amortecedor.jpeg',
    category: 'amortecedores',
  },
  {
    id: 8,
    name: 'chupeta para skate',
    price: 15.0,
    image: 'news/chupeta.jpeg',
    category: 'amortecedores',
  },
  {
    id: 9,
    name: 'Lixa Milk',
    price: 60.0,
    image: 'news/lixamilk.jpeg',
    category: 'acessorios',
  },
  {
    id: 10,
    name: 'Lixa Visible',
    price: 59.99,
    image: 'news/lixavisible.jpeg',
    category: 'acessorios',
  },
  {
    id: 11,
    name: 'Lixa Nacional',
    price: 29.99,
    image: 'produtos/lixa.webp',
    category: 'acessorios',
  },
  {
    id: 12,
    name: 'Rolamento Abec9',
    price: 45.99,
    image: 'produtos/rolamento/abec9.jpg',
    category: 'rolamentos',
  },
  {
    id: 13,
    name: 'Rolamento Bones Big Balls',
    price: 144.99,
    image: 'produtos/rolamento/bonesbill.jpg',
    category: 'rolamentos',
  },
  {
    id: 14,
    name: 'Rolamento Bones Reds',
    price: 144.99,
    image: 'produtos/rolamento/bonesred.jpg',
    category: 'rolamentos',
  },
  {
    id: 15,
    name: 'Rodas Mosca red 53mm',
    price: 180.0,
    image: 'news/rodamosca.jpeg',
    category: 'rodas',
  },
  {
    id: 16,
    name: 'TRUCK ESSENCIA STRONGER',
    price: 310.0,
    image: 'news/stronger.jpeg',
    category: 'trucks',
  },
  {
    id: 17,
    name: 'truck skate',
    price: 139.99,
    image: 'news/truck.jpeg',
    category: 'trucks',
  },
  {
    id: 18,
    name: 'truck Intruder 139mm',
    price: 310.0,
    image: 'news/INTRUDER.jpg',
    category: 'trucks',
  },
  {
    id: 19,
    name: 'TRUCK INTRUDER POWER GIRL 139mm',
    price: 310.0,
    image: 'news/POWER_GIRL.jpeg',
    category: 'trucks',
  },
  {
    id: 20,
    name: 'Rodas cbgang',
    price: 80.0,
    image: 'news/rodacb.jpeg',
    category: 'rodas',
  },
  {
    id: 21,
    name: 'Parafuso colorido PIG',
    price: 44.99,
    image: 'produtos/parafuso/parafusopig.jpg',
    category: 'parafusos',
  },
  {
    id: 22,
    name: 'porca color nuts dourada',
    price: 24.99,
    image: 'produtos/parafuso/porcadourada.jpg',
    category: 'parafusos',
  },
  {
    id: 23,
    name: 'porca central color',
    price: 24.99,
    image: 'news/porcacentralcolor.jpeg',
    category: 'parafusos',
  },
  {
    id: 24,
    name: 'porca central',
    price: 20.0,
    image: 'news/porcacentral.jpeg',
    category: 'parafusos',
  },
  {
    id: 25,
    name: 'parafuso central',
    price: 25.0,
    image: 'news/parafusocentral.jpeg',
    category: 'parafusos',
  },
  {
    id: 26,
    name: 'porca color nuts prata',
    price: 24.99,
    image: 'produtos/parafuso/porcaprata.jpg',
    category: 'parafusos',
  },
  {
    id: 27,
    name: 'Rolamento Speedballs',
    price: 50.0,
    image: 'produtos/rolamento/rolamento_speed.jpg',
    category: 'rolamentos',
  },
  {
    id: 28,
    name: 'Rolamento krome',
    price: 50.0,
    image: 'produtos/rolamento/rolamento_krome.jpg',
    category: 'rolamentos',
  },
  {
    id: 29,
    name: 'Rolamento california',
    price: 50.0,
    image: 'produtos/rolamento/rolamento_california.jpg',
    category: 'rolamentos',
  },
  {
    id: 30,
    name: 'Rolamento kolami',
    price: 50.0,
    image: 'produtos/rolamento/rolamento_kolami.jpg',
    category: 'rolamentos',
  },
  {
    id: 31,
    name: 'Roda EMEX gringa 53mm',
    price: 180.0,
    image: 'news/roda_emex.jpg',
    category: 'rodas',
  },
  {
    id: 32,
    name: 'Roda Shock 50mm',
    price: 100.0,
    image: 'news/roda_shock.jpg',
    category: 'rodas',
  },
  {
    id: 34,
    name: 'chave T',
    price: 50.0,
    image: 'produtos/parafuso/chave_t.jpg',
    category: 'parafusos',
  },
  {
    id: 35,
    name: 'chave Y com torniquete',
    price: 80.0,
    image: 'produtos/parafuso/chave_y.jpeg',
    category: 'parafusos',
  },
  {
    id: 36,
    name: 'Parafuso Central Vazado Stronger',
    price: 35.0,
    image: 'produtos/parafuso/central_vazado.jpeg',
    category: 'parafusos',
  },
  {
    id: 37,
    name: 'porca para eixo truck',
    price: 15.0,
    image: 'produtos/parafuso/PORCA_EIXO.png',
    category: 'parafusos',
  },
  {
    id: 38,
    name: 'Parafuso de Base Kronic',
    price: 30.0,
    image: 'produtos/parafuso/kronic_pbase.jpg',
    category: 'parafusos',
  },
  {
    id: 39,
    name: 'Parafuso de Base Superior',
    price: 35.0,
    image: 'produtos/parafuso/Superior_pbase.jpg',
    category: 'parafusos',
  },
];
